"""
recipe.py  --  Stage 2: turn the detected manifest into a Dockerfile.

This is the line we keep talking about: the machine writes the recipe, not you.
"""

SYSTEM_DEPS = {
    "Rglpk": ["libglpk40"],
    "sf": ["libgdal-dev", "libgeos-dev", "libproj-dev"],
    "xml2": ["libxml2-dev"],
    "curl": ["libcurl4-openssl-dev"],
    "openssl": ["libssl-dev"],
    "httr": ["libcurl4-openssl-dev", "libssl-dev"],
    "ragg": ["libfreetype6-dev", "libpng-dev", "libtiff5-dev", "libjpeg-dev"],
    "systemfonts": ["libfontconfig1-dev", "libfreetype6-dev"],
}


def detect_system_deps(manifest):
    deps = set()

    for pkg in manifest["packages"]:
        name = pkg["name"]
        if name in SYSTEM_DEPS:
            deps.update(SYSTEM_DEPS[name])

    return sorted(deps)


def generate_dockerfile(manifest):
    r_version = manifest["r_version"]

    lines = []
    lines.append("# Dockerfile  --  AUTO-GENERATED by reprocheck from the package contents.")
    lines.append("# Review it before trusting it; auto-detection is a first guess, not gospel.")
    lines.append("")
    lines.append(f"FROM rocker/r-ver:{r_version}")
    lines.append("")
    lines.append("WORKDIR /project")
    lines.append("")

    system_deps = detect_system_deps(manifest)

    if system_deps:
        lines.append("# System libraries inferred from detected R packages.")
        joined = " ".join(system_deps)
        lines.append(
            f"RUN apt-get update && apt-get install -y --no-install-recommends {joined} "
            "&& rm -rf /var/lib/apt/lists/*"
        )
        lines.append("")

    if manifest["has_renv_lock"]:
        lines.append("# This package shipped an renv.lock, so restore the exact pinned versions.")
        lines.append("COPY renv.lock renv.lock")
        lines.append(
            'RUN R -e "install.packages(\'renv\'); renv::restore(lockfile=\'renv.lock\')" '
            '&& rm -rf /root/.cache/R/renv/source'
        )
    else:
        pkgs = [p["name"] for p in manifest["packages"]]

        if pkgs:
            lines.append("# No lockfile found, so install the detected packages.")
            lines.append("# WARNING: versions are not pinned.")
            quoted = ", ".join(f"'{p}'" for p in pkgs)
            lines.append(f'RUN R -e "install.packages(c({quoted}))"')
        else:
            lines.append("# No add-on packages detected; base R only.")

    lines.append("")

    entry = manifest["entry_script"]

    if entry:
        lines.append(f'CMD ["Rscript", "{entry}"]')
    else:
        lines.append("# Entry script could not be guessed. Set the script to run here:")
        lines.append('# CMD ["Rscript", "code/your_master_script.R"]')

    return "\n".join(lines) + "\n"
